[[ssht]]
arch = "aarch64"
git-tree-sha1 = "1d88b2afcb6ebdadffecbe1455939a985e511f37"
os = "macos"

    [[ssht.download]]
    sha256 = "bb02be53fbde6bc3180e7955824f810621928e3998a29c1f2a10d694a8e7ac0b"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.aarch64-apple-darwin.tar.gz"
[[ssht]]
arch = "aarch64"
git-tree-sha1 = "b603c06e8c2b90654e2dede677c1f618afad434b"
libc = "glibc"
os = "linux"

    [[ssht.download]]
    sha256 = "84d7f77260a4671348e00e791e121ea073ace66e93afe19d84051f42c1bb7b35"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.aarch64-linux-gnu.tar.gz"
[[ssht]]
arch = "aarch64"
git-tree-sha1 = "1967687f0eefaa0326c5e915921517d112e3ccdd"
libc = "musl"
os = "linux"

    [[ssht.download]]
    sha256 = "2a2f5c1d4c4d5ba3e7a35587bdfdb47cd2b032ac822bd00cbc1d2874bf7ad7b3"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.aarch64-linux-musl.tar.gz"
[[ssht]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f31f2fc8b00474b9b5eb0ad606d4138813b36512"
libc = "glibc"
os = "linux"

    [[ssht.download]]
    sha256 = "429c429c1c24fdf71e09e9e1452b8d63ad7199a392660ff3ad6dab4034a2f2b0"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.armv6l-linux-gnueabihf.tar.gz"
[[ssht]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "53d7e68c162531f2670bea7ae3d027e5f19d868a"
libc = "musl"
os = "linux"

    [[ssht.download]]
    sha256 = "defb5856ee18084a0ec02289dad1515cf1e8eb302fc640974a1f392949ce644f"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.armv6l-linux-musleabihf.tar.gz"
[[ssht]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aea443b5521840252d8692d78ac122511df702dc"
libc = "glibc"
os = "linux"

    [[ssht.download]]
    sha256 = "725186b811b98cefbbd2faaa3978ea2d93d98268c6bfcd31ed8f9569a57bedde"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.armv7l-linux-gnueabihf.tar.gz"
[[ssht]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2107f0f02ccd095183c1c339f66275241dc168db"
libc = "musl"
os = "linux"

    [[ssht.download]]
    sha256 = "39d08de9e3327ed224607b0806bf5e80e8500556452c77be40b5fc57f442926b"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.armv7l-linux-musleabihf.tar.gz"
[[ssht]]
arch = "i686"
git-tree-sha1 = "b058472e376e9384e560e5faacff7ae558ca6402"
libc = "glibc"
os = "linux"

    [[ssht.download]]
    sha256 = "e65e1b47be264fce6cb616dcacd3d9034a96865d953e11d8f66dae1571cba19d"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.i686-linux-gnu.tar.gz"
[[ssht]]
arch = "i686"
git-tree-sha1 = "784201ad628086c67e95bfb1444b89fb1829127e"
libc = "musl"
os = "linux"

    [[ssht.download]]
    sha256 = "60a33e5a971808872497beecd218341d9ca5b74c15b7c61ee8e12a9fa58f8e23"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.i686-linux-musl.tar.gz"
[[ssht]]
arch = "i686"
git-tree-sha1 = "c2a390a8b9ba9b69c79ad36349361098dc1f2f03"
os = "windows"

    [[ssht.download]]
    sha256 = "287cb2b95b821e20effd7a5c965c230adc4d35728366b31192e5d21b42fae833"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.i686-w64-mingw32.tar.gz"
[[ssht]]
arch = "powerpc64le"
git-tree-sha1 = "20ae8f8b8c8af35e95d337230d66c5a6c3569188"
libc = "glibc"
os = "linux"

    [[ssht.download]]
    sha256 = "295f4652147003a238428b0212679f5e58acb32fc4a5866ef4ade7ac6afa795c"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.powerpc64le-linux-gnu.tar.gz"
[[ssht]]
arch = "x86_64"
git-tree-sha1 = "22ab0c3e12d90342b12cf8b34fbe702f048b503f"
os = "macos"

    [[ssht.download]]
    sha256 = "248245c4ff3f0ac051ff8b99b1c8499989917ab5993a24460ccd725661a3fd96"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.x86_64-apple-darwin.tar.gz"
[[ssht]]
arch = "x86_64"
git-tree-sha1 = "3813be9580b4d801e4981b07aa6fa2b9e8797471"
libc = "glibc"
os = "linux"

    [[ssht.download]]
    sha256 = "6ca25d46f7a7abc209f965c8ce8418091b2b75c2869d7f5dd7e407b07930677a"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.x86_64-linux-gnu.tar.gz"
[[ssht]]
arch = "x86_64"
git-tree-sha1 = "d6e7b7921368dbcdd9340fcaeeabf02596b9810e"
libc = "musl"
os = "linux"

    [[ssht.download]]
    sha256 = "f9fda25863be8ddb4375ac34c95f8a7530b08dcdb34c1fa832a2b19f2d933109"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.x86_64-linux-musl.tar.gz"
[[ssht]]
arch = "x86_64"
git-tree-sha1 = "272138670ee202a6b6cc971df37e60431e658d69"
os = "freebsd"

    [[ssht.download]]
    sha256 = "31716efd11204caa6a802ea59a613464b7a8596e8283c5a9bdc1a52b0e2261c0"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.x86_64-unknown-freebsd.tar.gz"
[[ssht]]
arch = "x86_64"
git-tree-sha1 = "d3f8e8849a1d20067ef0f8417dd4be8862b4793c"
os = "windows"

    [[ssht.download]]
    sha256 = "214abf5990847d97a3c543aed1045d838302dd1d8b14e2f2f3df6edc8b298abd"
    url = "https://github.com/JuliaBinaryWrappers/ssht_jll.jl/releases/download/ssht-v1.5.2+0/ssht.v1.5.2.x86_64-w64-mingw32.tar.gz"
