# Autogenerated wrapper script for ssht_jll for x86_64-w64-mingw32
export libssht

using FFTW_jll
JLLWrappers.@generate_wrapper_header("ssht")
JLLWrappers.@declare_library_product(libssht, "libssht.dll")
function __init__()
    JLLWrappers.@generate_init_header(FFTW_jll)
    JLLWrappers.@init_library_product(
        libssht,
        "bin\\libssht.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
